name: 'BlueRacer'
description: 'Compare test durations'
author: 'tamniteo'
inputs:
  durations-file:
    required: true
    description: 'path to the durations file'
    default: 'test_durations.csv'
  percentage-warn:
    required: false
    description: '% of change that yields warning'
    default: '10'
  percentage-error:
    required: false
    description: '% of change that yields error'
    default: '30'
runs:
  using: 'node16'
  main: 'dist/index.js'
